UPDATE mmo SET uuid=$player_uuid WHERE uuid=$player_uuid;
UPDATE mmo SET exp=$exp WHERE uuid=$player_uuid;
UPDATE mmo SET health=$health WHERE uuid=$player_uuid;
UPDATE mmo SET health_before=$health_before WHERE uuid=$player_uuid;
UPDATE mmo SET strength=$strength WHERE uuid=$player_uuid;
UPDATE mmo SET agility=$agility WHERE uuid=$player_uuid;
UPDATE mmo SET luck=$luck WHERE uuid=$player_uuid;
UPDATE mmo SET intelligence=$intelligence WHERE uuid=$player_uuid;
UPDATE mmo SET magic=$magic WHERE uuid=$player_uuid;
UPDATE mmo SET magic_max=$magic_max WHERE uuid=$player_uuid;
UPDATE mmo SET endurance=$endurance WHERE uuid=$player_uuid;
UPDATE mmo SET skillpoints=$skillpoints WHERE uuid=$player_uuid;
UPDATE mmo SET battlelog=$battlelog WHERE uuid=$player_uuid;
UPDATE mmo SET statusbar=$statusbar WHERE uuid=$player_uuid;
UPDATE mmo SET fraction=$fraction WHERE uuid=$player_uuid;
UPDATE mmo SET level=$level WHERE uuid=$player_uuid
